"""cuda-translator test suite (unittest, stdlib only).

Every test is grounded in real NVIDIA artifacts in examples/artifacts
(nvcc 12.9.86 / NVRTC 12.9; provenance in docs/ground-truth.md).
"""
from __future__ import annotations

import base64
import json
import os
import struct
import sys
import unittest
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE / "scripts"))

from cuda_translator import fatbin, elf, pe, ptx, interpreter, pipeline  # noqa: E402
from cuda_translator.ir import reachable_unsupported  # noqa: E402
from cuda_translator.opencl import emit_program, emit_kernel, TranslationAbort  # noqa: E402
from cuda_translator.numeric_oracles import (  # noqa: E402
    fma_rn_f32, f32_mul_rn, f32_add_rn, f32_bits, bits_f32,
)

ART = HERE / "examples" / "artifacts"


def f32(x: float) -> float:
    return struct.unpack("<f", struct.pack("<f", x))[0]


def rb(name: str) -> bytes:
    return (ART / name).read_bytes()


def rt(name: str) -> str:
    return (ART / name).read_text(encoding="utf-8", errors="replace")


class TestFatbinContainers(unittest.TestCase):
    """Oracle-verified container parsing (docs/ground-truth.md)."""

    def test_compressed_ptx_matches_nvidia_uncompressed_fatbin(self):
        comp = fatbin.parse(rb("vector_add_sm75.fatbin"))
        plain = fatbin.parse(rb("vector_add_sm75_nocompress.fatbin"))
        ce = [e for e in comp.entries if e.is_ptx][0]
        ue = [e for e in plain.entries if e.is_ptx][0]
        self.assertTrue(ce.compressed)
        self.assertFalse(ue.compressed)
        self.assertEqual(ce.payload, ue.payload)  # byte-for-byte vs NVIDIA

    def test_fatbin_elf_payload_equals_standalone_cubin(self):
        fb = fatbin.parse(rb("vector_add_sm75.fatbin"))
        ee = [e for e in fb.entries if e.is_elf][0]
        self.assertEqual(ee.payload, rb("vector_add_sm75.cubin"))

    def test_outer_size_field_excludes_header(self):
        data = rb("vector_add_sm75.fatbin")
        magic, ver, hs, size = struct.unpack_from("<IHHQ", data, 0)
        self.assertEqual(magic, 0xBA55ED50)
        self.assertEqual(hs + size, len(data))  # header NOT included in size

    def test_pe_scan_finds_embedded_fatbin_byte_exact(self):
        scan = pe.scan(rb("vector_add_host.exe"))
        self.assertTrue(scan.is_pe)
        self.assertEqual(scan.arch, "x86-64")
        ref = rb("vector_add_sm75.fatbin")
        self.assertTrue(any(h.data == ref for h in scan.hits))

    def test_elf_arch_across_real_cubins(self):
        for sm in (50, 60, 61, 70, 75, 80, 86, 89, 90, 100, 120):
            path = ART / f"vector_add_sm{sm}.cubin"
            if not path.exists():
                continue
            cub = elf.parse(path.read_bytes())
            self.assertEqual(cub.arch, f"sm_{sm}")
            self.assertEqual({s.name for s in cub.entry_symbols()},
                             {"vector_add", "saxpy"})


class TestPTXFrontend(unittest.TestCase):
    def test_nvcc_ptx_clean_and_fully_resolved(self):
        res = ptx.parse_ptx(rt("vector_add_sm75.ptx"))
        self.assertEqual(res.diagnostics, [])
        self.assertEqual(res.notes["ptx_version"], (8, 8))
        self.assertEqual(res.notes["target"], "sm_75")
        for k in res.kernels:
            self.assertEqual(reachable_unsupported(k), [], k.name)
            for inst in k.body:
                if inst.op in ("ld_global", "st_global"):
                    self.assertIsNotNone(inst.addr)
                    self.assertIsNotNone(inst.addr.base_param)
        ptrs = {p.name for p in res.kernels[0].params if p.is_pointer}
        self.assertEqual(len(ptrs), 3)  # a, b, c

    def test_nvrtc_ptx_independent_path_also_clean(self):
        res = ptx.parse_ptx(rt("vector_add_sm75_nvrtc.ptx"))
        self.assertEqual(res.diagnostics, [])
        self.assertEqual({k.name for k in res.kernels}, {"vector_add", "saxpy"})

    def test_embedded_fatbin_ptx_translatable(self):
        scan = pe.scan(rb("vector_add_host.exe"))
        fb = [h for h in scan.hits if h.size == 4928][0].parse()
        text = [e for e in fb.entries if e.is_ptx][0].text()
        res = ptx.parse_ptx(text)
        self.assertEqual(res.diagnostics, [])
        self.assertTrue(all(not reachable_unsupported(k) for k in res.kernels))


class TestBackendSemantics(unittest.TestCase):
    def setUp(self):
        self.res = ptx.parse_ptx(rt("vector_add_sm75.ptx"))

    def test_header_and_sources(self):
        header, sources = emit_program(self.res)
        self.assertEqual(set(sources), {"vector_add", "saxpy"})
        self.assertEqual(header.strip().splitlines()[0],
                         "// Generated by cuda-translator (OpenCL C backend)")

    def test_byte_addressing_not_double_scaled(self):
        src = emit_kernel([k for k in self.res.kernels if k.name == "vector_add"][0])
        # scale must be applied exactly once, on a uchar* base
        self.assertIn("(__global uchar const *)(p_vector_add_param_1)) + ((size_t)(r__r1) * (4))",
                      src)

    def test_selp_uses_predicate_as_fourth_ptx_operand(self):
        source_ptx = r"""
.version 7.8
.target sm_52
.address_size 64
.visible .entry selp_test(
    .param .u64 out
)
{
    .reg .pred %p<2>;
    .reg .b32 %r<4>;
    .reg .b64 %rd<3>;
    ld.param.u64 %rd1, [out];
    cvta.to.global.u64 %rd2, %rd1;
    mov.u32 %r1, 11;
    mov.u32 %r2, 22;
    setp.eq.u32 %p1, %r1, 11;
    selp.u32 %r3, %r1, %r2, %p1;
    st.global.u32 [%rd2], %r3;
    ret;
}
"""
        result = ptx.parse_ptx(source_ptx)
        src = emit_program(result)[1]["selp_test"]
        self.assertIn("r__p1", src)
        self.assertIn("? ((uint)(r__r1)) : ((uint)(r__r2))", src)

    def test_fp_neg_and_pred_not_preserve_ptx_types(self):
        source_ptx = r"""
.version 7.8
.target sm_52
.address_size 64
.visible .entry unary_test(
    .param .u64 out
)
{
    .reg .pred %p<3>;
    .reg .f64 %fd<3>;
    .reg .b64 %rd<3>;
    ld.param.u64 %rd1, [out];
    cvta.to.global.u64 %rd2, %rd1;
    mov.f64 %fd1, 0d3ff0000000000000;
    neg.f64 %fd2, %fd1;
    setp.eq.f64 %p1, %fd1, %fd1;
    not.pred %p2, %p1;
    st.global.f64 [%rd2], %fd2;
    ret;
}
"""
        result = ptx.parse_ptx(source_ptx)
        src = emit_program(result)[1]["unary_test"]
        self.assertIn("-((double)(r__fd1))", src)
        self.assertIn("!((uchar)(r__p1))", src)
        self.assertNotIn("-((uint)(r__fd1))", src)

    def test_setp_s16_reinterprets_b16_storage_signed(self):
        source_ptx = r"""
.version 7.8
.target sm_52
.address_size 64
.visible .entry signed_edge(
    .param .u64 p
)
{
    .reg .b64 %rd<3>;
    .reg .b16 %rs<2>;
    .reg .pred %p<2>;
    ld.param.u64 %rd1, [p];
    cvta.to.global.u64 %rd2, %rd1;
    ld.global.s8 %rs1, [%rd2];
    setp.gt.s16 %p1, %rs1, 0;
    ret;
}
"""
        k = ptx.parse_ptx(source_ptx).kernels[0]
        out = emit_kernel(k)
        self.assertIn("((short)(r__rs1)) > ((short)(0))", out)


    def test_setp_leu_float_includes_unordered_nan_case(self):
        source_ptx = r"""
.version 7.8
.target sm_52
.address_size 64
.visible .entry cmp_test(
    .param .u64 out
)
{
    .reg .pred %p<2>;
    .reg .f64 %fd<3>;
    .reg .b64 %rd<3>;
    ld.param.u64 %rd1, [out];
    cvta.to.global.u64 %rd2, %rd1;
    mov.f64 %fd1, 0d0000000000000000;
    mov.f64 %fd2, 0d3ff0000000000000;
    setp.leu.f64 %p1, %fd1, %fd2;
    ret;
}
"""
        result = ptx.parse_ptx(source_ptx)
        src = emit_program(result)[1]["cmp_test"]
        self.assertIn("isnan(", src)
        self.assertIn("<=", src)

    def test_cvt_preserves_source_signedness_and_width(self):
        source_ptx = r"""
.version 7.8
.target sm_52
.address_size 64
.visible .entry cvt_test(
    .param .u64 out
)
{
    .reg .b32 %r<3>;
    .reg .b64 %rd<4>;
    .reg .f64 %fd<2>;
    ld.param.u64 %rd1, [out];
    cvta.to.global.u64 %rd2, %rd1;
    mov.u32 %r1, 4294967295;
    cvt.s64.s32 %rd3, %r1;
    cvt.rn.f64.s64 %fd1, %rd3;
    st.global.f64 [%rd2], %fd1;
    ret;
}
"""
        result = ptx.parse_ptx(source_ptx)
        src = emit_program(result)[1]["cvt_test"]
        self.assertIn("((int)(r__r1))", src)
        self.assertIn("((long)(r__rd3))", src)
        self.assertIn("((double)", src)

    def test_bar_sync_fences_local_and_global_memory(self):
        source_ptx = r"""
.version 7.8
.target sm_52
.address_size 64
.visible .entry barrier_test()
{
    bar.sync 0;
    ret;
}
"""
        result = ptx.parse_ptx(source_ptx)
        src = emit_program(result)[1]["barrier_test"]
        self.assertIn(
            "CLK_LOCAL_MEM_FENCE | CLK_GLOBAL_MEM_FENCE",
            src,
        )

    def test_mixed_width_global_access_uses_instruction_width(self):
        source_ptx = r"""
.version 7.8
.target sm_52
.address_size 64
.visible .entry mixed_width(
    .param .u64 p
)
{
    .reg .b64 %rd<3>;
    .reg .u64 %r<2>;
    .reg .f64 %fd<2>;
    ld.param.u64 %rd1, [p];
    cvta.to.global.u64 %rd2, %rd1;
    ld.global.u64 %r1, [%rd2];
    ld.global.f64 %fd1, [%rd2];
    ret;
}
"""
        k = ptx.parse_ptx(source_ptx).kernels[0]
        out = emit_kernel(k)
        self.assertIn("__global uchar* restrict", out)
        self.assertIn("__global ulong const *", out)
        self.assertIn("__global double const *", out)


    def test_fma_lowered_to_opencl_fma(self):
        src = emit_kernel([k for k in self.res.kernels if k.name == "saxpy"][0])
        self.assertIn("fma(", src)
        self.assertIn("get_group_id(0)", src)
        self.assertIn("get_local_id(0)", src)

    def test_fail_closed_on_atom(self):
        hres = ptx.parse_ptx(rt("histogram_sm75.ptx"))
        hist = [k for k in hres.kernels if k.name == "histogram"][0]
        bad = reachable_unsupported(hist)
        self.assertEqual(len(bad), 1)
        with self.assertRaises(TranslationAbort):
            emit_kernel(hist)

    def test_bin_classify_data_dependent_cfg_in_subset(self):
        hres = ptx.parse_ptx(rt("histogram_sm75.ptx"))
        bc = [k for k in hres.kernels if k.name == "bin_classify"][0]
        self.assertEqual(reachable_unsupported(bc), [])
        emit_kernel(bc)  # structured multi-branch guard idiom lowers


class TestExactOracles(unittest.TestCase):
    def test_oracle_matches_native_fmaf(self):
        import ctypes
        import random
        ucrt = ctypes.CDLL("ucrtbase.dll")
        ucrt.fmaf.restype = ctypes.c_float
        ucrt.fmaf.argtypes = [ctypes.c_float] * 3
        random.seed(4242)
        for _ in range(5000):
            a = f32(random.uniform(-1e5, 1e5))
            b = f32(random.uniform(-1e5, 1e5))
            c = f32(random.uniform(-1e5, 1e5))
            want = fma_rn_f32(f32_bits(a), f32_bits(b), f32_bits(c))
            self.assertEqual(f32_bits(ucrt.fmaf(a, b, c)), want)

    def test_fused_vs_unfused_divergence_exists(self):
        import random
        random.seed(1)
        diffs = 0
        for _ in range(2000):
            a = f32(random.uniform(-1e4, 1e4))
            b = f32(random.uniform(-1e4, 1e4))
            c = f32(random.uniform(-1e4, 1e4))
            if fma_rn_f32(f32_bits(a), f32_bits(b), f32_bits(c)) != \
               f32_add_rn(f32_mul_rn(f32_bits(a), f32_bits(b)), f32_bits(c)):
                diffs += 1
        self.assertGreater(diffs, 100)


class TestInterpreter(unittest.TestCase):
    N = 1024

    def _run_saxpy(self, name: str):
        res = ptx.parse_ptx(rt(name))
        k = [x for x in res.kernels if x.name == "saxpy"][0]
        import random
        random.seed(11)
        n = self.N
        xs = [f32(random.uniform(-1e4, 1e4)) for _ in range(n)]
        ys = [f32(random.uniform(-1e4, 1e4)) for _ in range(n)]
        alpha = f32(-3.75)
        o = bytearray(n * 4)
        interpreter.run_kernel(
            k, {"saxpy_param_0": alpha, "saxpy_param_4": n}, (n,), (256,),
            {"saxpy_param_1": bytearray(struct.pack(f"<{n}f", *xs)),
             "saxpy_param_2": bytearray(struct.pack(f"<{n}f", *ys)),
             "saxpy_param_3": o})
        got = struct.unpack(f"<{n}f", bytes(o))
        fused = sum(1 for i in range(n)
                    if got[i] == bits_f32(fma_rn_f32(f32_bits(xs[i]), f32_bits(alpha),
                                                     f32_bits(ys[i]))))
        unfused = sum(1 for i in range(n)
                      if got[i] == bits_f32(f32_add_rn(f32_mul_rn(f32_bits(xs[i]),
                                                                  f32_bits(alpha)),
                                                       f32_bits(ys[i]))))
        return n, fused, unfused

    def test_interpreter_vector_add_exact(self):
        res = ptx.parse_ptx(rt("vector_add_sm75.ptx"))
        k = [x for x in res.kernels if x.name == "vector_add"][0]
        n = self.N
        a = bytearray(struct.pack(f"<{n}f", *[f32(i * 0.5) for i in range(n)]))
        b = bytearray(struct.pack(f"<{n}f", *[f32(i * 2.0) for i in range(n)]))
        c = bytearray(n * 4)
        interpreter.run_kernel(k, {"vector_add_param_3": n}, (n,), (256,),
                               {"vector_add_param_0": a,
                                "vector_add_param_1": b,
                                "vector_add_param_2": c})
        got = struct.unpack(f"<{n}f", bytes(c))
        want = [bits_f32(f32_add_rn(f32_bits(i * 0.5), f32_bits(i * 2.0)))
                for i in range(n)]
        self.assertEqual(list(got), want)

    def test_interpreter_preserves_fma_contraction(self):
        n, fused, unfused = self._run_saxpy("vector_add_sm75.ptx")
        self.assertEqual(fused, n)  # default build: fused semantics
        self.assertLess(unfused, n)  # and provably NOT unfused

    def test_interpreter_nofmad_is_unfused(self):
        if not (ART / "vector_add_sm75_nofmad.ptx").exists():
            self.skipTest("nofmad fixture not built")
        n, fused, unfused = self._run_saxpy("vector_add_sm75_nofmad.ptx")
        self.assertEqual(unfused, n)
        self.assertLess(fused, n)

    def test_illegal_ndrange_rejected(self):
        res = ptx.parse_ptx(rt("vector_add_sm75.ptx"))
        k = [x for x in res.kernels if x.name == "vector_add"][0]
        with self.assertRaises(ValueError):
            interpreter.run_kernel(k, {"vector_add_param_3": 100}, (1000,), (256,),
                                   {"vector_add_param_0": bytearray(400),
                                    "vector_add_param_1": bytearray(400),
                                    "vector_add_param_2": bytearray(400)})


class TestPipeline(unittest.TestCase):
    def test_detect_all_kinds(self):
        self.assertEqual(pipeline.detect_input(rb("vector_add_sm75.ptx")), "ptx")
        self.assertEqual(pipeline.detect_input(rb("vector_add_sm75.cubin")), "cubin")
        self.assertEqual(pipeline.detect_input(rb("vector_add_sm75.fatbin")), "fatbin")
        self.assertEqual(pipeline.detect_input(rb("vector_add_host.exe")), "pe")

    def test_translate_ptx_text_strict_fails_closed(self):
        hist = rt("histogram_sm75.ptx")
        with self.assertRaises(Exception) as cm:
            pipeline.translate_ptx_text_strict(hist)
        self.assertIn("histogram", str(cm.exception))

    def test_translate_fatbin_end_to_end(self):
        result = pipeline.translate_input(rb("vector_add_sm75.fatbin"))
        self.assertEqual(set(result["kernels"]), {"vector_add", "saxpy"})

    def test_analyze_pe_reports_embedded(self):
        rep = pipeline.analyze_input(rb("vector_add_host.exe"))
        self.assertEqual(rep["kind"], "pe")
        self.assertTrue(any(f["size"] == 4928 for f in rep["embedded_fatbins"]))


class TestPackaging(unittest.TestCase):
    def test_bundled_verification_fixture_is_available(self):
        from importlib import resources
        text = (
            resources.files("cuda_translator")
            .joinpath("fixtures", "vector_add_sm75.ptx")
            .read_text(encoding="utf-8")
        )
        self.assertIn(".entry vector_add", text)
        self.assertIn(".entry saxpy", text)

    def test_packaged_opencl_runner_imports_without_checkout_scripts(self):
        from cuda_translator import opencl_runner
        self.assertTrue(callable(opencl_runner.first_device))



if __name__ == "__main__":
    unittest.main(verbosity=2)
